name: Build Site
run-name: "Jekyll built on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"

on:
  push:
    branches:
      - '[0-9]+-**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    uses: Mimis-Gildi/fluffle/.github/workflows/pages-build.yml@main
    secrets: inherit
    permissions:
      contents: read
